from __future__ import annotations

USERS = {
    "U001": {
        "real_person_id": "RP-0001",
        "name": "张三",
        "position": "产品推广专员",
        "domain": "制造业集团/产品推广部",
        "manager": "U002",
        "standard_resources": ["营销文案模板", "产品资料库只读", "内容初稿生成"],
        "permissions": {
            "receive_content_subtask": True,
            "classify_content_type": True,
            "read_source_material": True,
            "retrieve_knowledge": True,
            "use_template": True,
            "use_prompt": True,
            "dispatch_model": True,
            "generate_draft": True,
            "quality_check": True,
            "add_ai_label": True,
            "register_content_result": True,
            "deliver_result": True,
            "confirm_result": False,
            "freeze_result": False,
        },
    },
    "U002": {
        "real_person_id": "RP-0002",
        "name": "李四",
        "position": "品牌负责人",
        "domain": "制造业集团/产品推广部",
        "manager": None,
        "standard_resources": ["营销文案模板", "品牌规范", "对外内容确认"],
        "permissions": {
            "receive_content_subtask": True,
            "classify_content_type": True,
            "read_source_material": True,
            "retrieve_knowledge": True,
            "use_template": True,
            "use_prompt": True,
            "dispatch_model": True,
            "generate_draft": True,
            "quality_check": True,
            "add_ai_label": True,
            "register_content_result": True,
            "deliver_result": True,
            "confirm_result": True,
            "freeze_result": True,
        },
    },
    "U003": {
        "real_person_id": "RP-0003",
        "name": "王五",
        "position": "安全管理人员",
        "domain": "制造业集团/生产一部",
        "manager": "U006",
        "standard_resources": ["隐患整改通知书模板", "安全制度知识库", "内部公文草稿生成"],
        "permissions": {
            "receive_content_subtask": True,
            "classify_content_type": True,
            "read_source_material": True,
            "retrieve_knowledge": True,
            "use_template": True,
            "use_prompt": True,
            "dispatch_model": True,
            "generate_draft": True,
            "quality_check": True,
            "add_ai_label": True,
            "register_content_result": True,
            "deliver_result": True,
            "confirm_result": True,
            "freeze_result": False,
        },
    },
    "U004": {
        "real_person_id": "RP-0004",
        "name": "赵六",
        "position": "安全审计员",
        "domain": "集团审计",
        "manager": None,
        "standard_resources": ["审计日志查看", "结果冻结", "合规核查"],
        "permissions": {
            "receive_content_subtask": False,
            "classify_content_type": False,
            "read_source_material": True,
            "retrieve_knowledge": True,
            "use_template": False,
            "use_prompt": False,
            "dispatch_model": False,
            "generate_draft": False,
            "quality_check": True,
            "add_ai_label": True,
            "register_content_result": False,
            "deliver_result": False,
            "confirm_result": True,
            "freeze_result": True,
        },
    },
    "U005": {
        "real_person_id": "RP-0005",
        "name": "陈律师",
        "position": "律师",
        "domain": "法律服务行业/诉讼团队",
        "manager": "U007",
        "standard_resources": ["诉状模板", "答辩状模板", "案件材料只读", "AI 文书草稿"],
        "permissions": {
            "receive_content_subtask": True,
            "classify_content_type": True,
            "read_source_material": True,
            "retrieve_knowledge": True,
            "use_template": True,
            "use_prompt": True,
            "dispatch_model": True,
            "generate_draft": True,
            "quality_check": True,
            "add_ai_label": True,
            "register_content_result": True,
            "deliver_result": True,
            "confirm_result": True,
            "freeze_result": False,
        },
    },
}

POSITION_TO_USER = {
    "品牌负责人": "U002",
    "安全管理人员": "U003",
    "安全负责人": "U006",
    "律师": "U005",
    "审计员": "U004",
}

ACTION_CATALOG = {
    "receive_content_subtask": {"label": "接收流程执行引擎派发的内容产出子任务", "registered": True, "risk": "medium"},
    "classify_content_type": {"label": "判定文字成果类型并选择成文模式", "registered": True, "risk": "low"},
    "read_source_material": {"label": "读取依据资料", "registered": True, "risk": "medium"},
    "retrieve_knowledge": {"label": "引用知识库检索结果", "registered": True, "risk": "medium"},
    "use_template": {"label": "取用文字成果模板", "registered": True, "risk": "medium"},
    "use_prompt": {"label": "取用 1.6 上下文与提示词模板", "registered": True, "risk": "low"},
    "dispatch_model": {"label": "经 1.5 大模型调度提交生成任务", "registered": True, "risk": "medium"},
    "generate_draft": {"label": "生成文字初稿", "registered": True, "risk": "medium"},
    "quality_check": {"label": "核查模板要素、引用、数字和风险", "registered": True, "risk": "medium"},
    "add_ai_label": {"label": "添加 AI 生成待审核标注", "registered": True, "risk": "medium"},
    "register_content_result": {"label": "登记文字成果", "registered": True, "risk": "medium"},
    "deliver_result": {"label": "交回流程执行引擎", "registered": True, "risk": "medium"},
    "confirm_result": {"label": "真人确认文字成果", "registered": True, "risk": "high"},
    "freeze_result": {"label": "冻结内容成果", "registered": True, "risk": "high"},
}

SOURCE_MATERIALS = {
    "DATA-HAZARD-001": {
        "name": "隐患情况描述",
        "type": "business_fact",
        "owner_domain": "制造业集团/生产一部",
        "summary": "3 号车间配电柜周边存在临时堆放纸箱，消防通道局部被占用。",
        "allowed_actions": ["read_source_material"],
        "state": "active",
    },
    "KB-LAW-SAFE-001": {
        "name": "安全生产法规条款匹配结果",
        "type": "knowledge_result",
        "owner_domain": "制造业集团/生产一部",
        "summary": "法规要求保持疏散通道、安全出口、消防车通道畅通，不得占用、堵塞。",
        "allowed_actions": ["retrieve_knowledge", "read_source_material"],
        "state": "active",
    },
    "DATA-PRODUCT-001": {
        "name": "产品资料摘要",
        "type": "product_fact",
        "owner_domain": "制造业集团/产品推广部",
        "summary": "产品定位为面向种植基地的智能监测设备，核心卖点为远程监测、异常提醒和节省巡检时间。",
        "allowed_actions": ["read_source_material"],
        "state": "active",
    },
    "KB-BRAND-STYLE-001": {
        "name": "品牌表达规范",
        "type": "style_guide",
        "owner_domain": "制造业集团/产品推广部",
        "summary": "语言要求克制、专业、少夸张，避免绝对化承诺。",
        "allowed_actions": ["retrieve_knowledge", "read_source_material"],
        "state": "active",
    },
    "DATA-CASE-FACT-001": {
        "name": "案件事实描述",
        "type": "case_fact",
        "owner_domain": "法律服务行业/诉讼团队",
        "summary": "委托人因买卖合同履行争议准备起诉，对方未按约定期限支付尾款。",
        "allowed_actions": ["read_source_material"],
        "state": "active",
    },
    "KB-LEGAL-STRUCTURE-001": {
        "name": "诉状结构与类案文书引用",
        "type": "legal_structure",
        "owner_domain": "法律服务行业/诉讼团队",
        "summary": "民事起诉状通常包括当事人信息、诉讼请求、事实与理由、证据目录、落款等结构。",
        "allowed_actions": ["retrieve_knowledge", "read_source_material"],
        "state": "active",
    },
    "AGENT-CROP-NUTRITION-001": {
        "name": "作物营养专家分身",
        "type": "expert_agent",
        "owner_domain": "集团共享池",
        "summary": "用于演示从共享池取用专家分身，根据地块条件、作物阶段和规则接口位生成施肥方案。",
        "allowed_actions": ["retrieve_knowledge", "read_source_material"],
        "state": "active",
    },
    "SKILL-CROP-NUTRITION-STANDARD-001": {
        "name": "作物营养配方标准技能",
        "type": "digital_asset_skill",
        "owner_domain": "集团共享池",
        "summary": "记录作物营养诊断、配方建议、风险提醒和方案格式标准；本地仅作为数字资产技能引用。",
        "allowed_actions": ["retrieve_knowledge", "read_source_material"],
        "state": "active",
    },
    "SKILL-SUGARCANE-FERTILIZATION-001": {
        "name": "甘蔗全程施肥方案技能",
        "type": "digital_asset_skill",
        "owner_domain": "集团共享池",
        "summary": "记录甘蔗苗期、分蘖期、伸长期和成熟期的施肥建议结构；真实规则计算需由规则引擎承办。",
        "allowed_actions": ["retrieve_knowledge", "read_source_material"],
        "state": "active",
    },
    "DATA-GENERIC-CONTENT-INPUT": {
        "name": "通用内容任务输入占位",
        "type": "generic_content_input",
        "owner_domain": "流程执行引擎派发",
        "summary": "用于任务适配版承接未专门建模的文字类子任务；正式联调时应由流程执行传入真实资料、分析结论或知识库引用。",
        "allowed_actions": ["read_source_material"],
        "state": "active",
    },
}

TEMPLATES = {
    "TPL-RECTIFICATION-NOTICE": {
        "name": "整改通知书模板",
        "version": "v1.0",
        "content_type": "整改通知书",
        "required_sections": ["标题", "隐患事实", "适用依据", "整改要求", "完成期限", "审核签发"],
        "review_policy": "必须安全管理人员审核后定稿",
        "state": "active",
    },
    "TPL-MARKETING-BUNDLE": {
        "name": "营销文案组合模板",
        "version": "v1.0",
        "content_type": "多场景营销文案",
        "required_sections": ["产品课件要点", "手册文案", "海报文案", "公众号推文", "会议主持词", "销售话术"],
        "review_policy": "内部初稿可直接交付，对外发布前需品牌负责人确认",
        "state": "active",
    },
    "TPL-LEGAL-PLEADING": {
        "name": "法律文书草稿模板",
        "version": "v0.9",
        "content_type": "诉状/答辩状草稿",
        "required_sections": ["当事人信息占位", "诉讼请求", "事实与理由", "证据目录", "律师审核提示"],
        "review_policy": "必须律师审核后方可使用",
        "state": "active",
    },
    "TPL-EXPERT-PLAN": {
        "name": "专家方案文档模板",
        "version": "v0.1",
        "content_type": "专家施肥方案",
        "required_sections": ["基础信息", "阶段方案", "配方与用量", "风险处置", "计算说明", "下载与存档"],
        "review_policy": "本地演示可直接交付初稿；正式推广、发文或开放共享前仍需按平台确认。",
        "state": "active",
    },
    "TPL-GENERIC-REPORT": {
        "name": "通用报告初稿模板",
        "version": "v0.2",
        "content_type": "报告/方案初稿",
        "required_sections": ["背景", "目标", "主要内容", "风险与待确认", "结论"],
        "review_policy": "内部初稿可返回；正式对外前需由流程执行组织真人确认。",
        "state": "active",
    },
    "TPL-GENERIC-ARTICLE": {
        "name": "通用文章/公众号初稿模板",
        "version": "v0.2",
        "content_type": "文章/公众号初稿",
        "required_sections": ["标题", "开头", "主体", "结尾", "待确认"],
        "review_policy": "内部初稿可返回；对外发布前需真人确认。",
        "state": "active",
    },
    "TPL-GENERIC-MEETING": {
        "name": "通用会议纪要/汇报稿模板",
        "version": "v0.2",
        "content_type": "会议纪要/汇报稿",
        "required_sections": ["会议背景", "讨论要点", "结论", "待办", "风险"],
        "review_policy": "会议记录不完整时只能作为结构化初稿返回。",
        "state": "active",
    },
    "TPL-GENERIC-SCRIPT": {
        "name": "通用话术/脚本模板",
        "version": "v0.2",
        "content_type": "话术/脚本初稿",
        "required_sections": ["场景", "开场", "主体话术", "结束语", "注意事项"],
        "review_policy": "内部初稿可返回；对外使用前需真人确认。",
        "state": "active",
    },
    "TPL-GENERIC-DRAFT": {
        "name": "通用文字初稿模板",
        "version": "v0.2",
        "content_type": "通用文字成果",
        "required_sections": ["任务理解", "初稿内容", "引用与依据", "待补充信息"],
        "review_policy": "仅作兜底初稿；正式任务应补齐更精确的能力和模板。",
        "state": "active",
    },
    "TPL-MISSING": {
        "name": "缺失模板示例",
        "version": "v0.0",
        "content_type": "未配置文字成果",
        "required_sections": [],
        "review_policy": "不可用",
        "state": "missing",
    },
}

SCENARIOS = {
    "REQ-054": {
        "title": "需求 54：依模板与法规生成整改通知书",
        "l4_request": "根据这条隐患情况和适用法规，生成一份规范的整改通知书初稿。",
        "content_type": "rectification_notice",
        "content_type_label": "整改通知书",
        "requested_service": "生成整改通知书初稿",
        "template_id": "TPL-RECTIFICATION-NOTICE",
        "source_material_refs": ["DATA-HAZARD-001", "KB-LAW-SAFE-001"],
        "expected_output": "一份整改通知书初稿和待审核材料包",
        "review_policy": "pending_human_confirmation",
        "approval_template": ["安全管理人员"],
        "risk_level": "high",
        "exit_policy": "pending_human_confirmation",
        "mock_drafts": [
            {
                "title": "关于 3 号车间配电柜周边消防通道占用问题的整改通知书（初稿）",
                "sections": [
                    {"heading": "隐患事实", "body": "经现场检查，3 号车间配电柜周边存在临时堆放纸箱情况，消防通道局部被占用。"},
                    {"heading": "适用依据", "body": "依据已匹配法规条款，相关场所应保持疏散通道、安全出口、消防车通道畅通。"},
                    {"heading": "整改要求", "body": "请责任部门立即清理临时堆放物，恢复消防通道畅通，并形成整改照片与复核记录。"},
                    {"heading": "完成期限", "body": "建议在 1 个工作日内完成整改，具体期限由安全管理人员审核确认。"},
                ],
                "unresolved_questions": ["责任部门和整改期限需由安全管理人员最终确认。"],
            }
        ],
    },
    "REQ-115": {
        "title": "需求 115：多类营销文案的批量初稿产出",
        "l4_request": "围绕智能监测设备，生成产品课件、手册、海报文案、公众号推文、会议主持词、销售话术等初稿。",
        "content_type": "marketing_bundle",
        "content_type_label": "营销文案组合",
        "requested_service": "生成多场景营销文案初稿",
        "template_id": "TPL-MARKETING-BUNDLE",
        "source_material_refs": ["DATA-PRODUCT-001", "KB-BRAND-STYLE-001"],
        "expected_output": "六类文字物料初稿",
        "review_policy": "direct_delivery_draft",
        "approval_template": [],
        "risk_level": "medium",
        "exit_policy": "direct_delivery",
        "mock_drafts": [
            {"title": "产品课件要点初稿", "sections": [{"heading": "核心信息", "body": "面向种植基地的智能监测设备，突出远程监测、异常提醒和节省巡检时间。"}], "unresolved_questions": []},
            {"title": "产品手册文案初稿", "sections": [{"heading": "产品简介", "body": "本设备帮助基地管理人员持续掌握现场状态，并在异常出现时及时提醒。"}], "unresolved_questions": []},
            {"title": "海报文案初稿", "sections": [{"heading": "主标题", "body": "让基地巡检从被动发现走向主动提醒"}, {"heading": "副文案", "body": "远程监测关键状态，减少重复巡检，把时间留给更重要的判断。"}], "unresolved_questions": ["海报图片、版式设计归多媒体生成引擎。"]},
            {"title": "公众号推文初稿", "sections": [{"heading": "开头", "body": "种植基地的现场管理，常常难在及时发现异常。本方案把关键状态接入远程监测，让管理人员更快掌握变化。"}], "unresolved_questions": []},
            {"title": "会议主持词初稿", "sections": [{"heading": "开场", "body": "各位同事，今天我们围绕基地智能监测设备的应用价值和推广计划进行说明。"}], "unresolved_questions": []},
            {"title": "销售话术初稿", "sections": [{"heading": "客户沟通", "body": "这套设备不是替代现场管理，而是帮您把高频巡检中的重复工作降下来，把异常提醒提前。"}], "unresolved_questions": []},
        ],
    },
    "LEGAL-001": {
        "title": "法律服务行业：案件文书草稿生成",
        "l4_request": "根据案件类型和事实描述，生成一份民事起诉状草稿，标注 AI 生成待审核。",
        "content_type": "legal_pleading",
        "content_type_label": "法律文书草稿",
        "requested_service": "生成诉状/答辩状草稿",
        "template_id": "TPL-LEGAL-PLEADING",
        "source_material_refs": ["DATA-CASE-FACT-001", "KB-LEGAL-STRUCTURE-001"],
        "expected_output": "一份法律文书草稿和律师审核材料包",
        "review_policy": "pending_human_confirmation",
        "approval_template": ["律师"],
        "risk_level": "high",
        "exit_policy": "pending_human_confirmation",
        "mock_drafts": [
            {
                "title": "民事起诉状草稿（AI 生成待审核）",
                "sections": [
                    {"heading": "诉讼请求", "body": "请求判令被告支付买卖合同项下尾款及相应违约责任。具体金额应由律师根据合同及付款凭证确认。"},
                    {"heading": "事实与理由", "body": "根据委托人提供的事实描述，双方存在买卖合同关系，对方未按约定期限支付尾款。"},
                    {"heading": "证据目录", "body": "合同文本、交付凭证、付款记录、催告记录等证据需由律师核验后列明。"},
                ],
                "unresolved_questions": ["当事人信息、金额、证据编号和诉讼请求表述必须由律师补齐并审核。"],
            }
        ],
    },
    "REQ-EXPERT-PLAN": {
        "title": "案例一：共享池专家分身生成施肥方案",
        "l4_request": "合作社需要一份桂中片区甘蔗全程施肥方案，要求说明不同阶段用肥建议、风险提醒和可下载文档。",
        "content_type": "expert_plan",
        "content_type_label": "专家施肥方案",
        "requested_service": "基于共享池专家分身生成施肥方案",
        "template_id": "TPL-EXPERT-PLAN",
        "source_material_refs": ["AGENT-CROP-NUTRITION-001", "SKILL-CROP-NUTRITION-STANDARD-001", "SKILL-SUGARCANE-FERTILIZATION-001"],
        "expected_output": "可下载的专家方案文档，含阶段方案、配方与用量、风险处置和计算说明",
        "review_policy": "direct_delivery_draft",
        "approval_template": [],
        "risk_level": "medium",
        "exit_policy": "direct_delivery",
        "mock_drafts": [
            {
                "title": "桂中片区甘蔗全程施肥方案（专家分身初稿）",
                "sections": [
                    {"heading": "基础信息", "body": "本方案面向桂中片区甘蔗种植地块，假设土壤偏酸、去年出现脱肥发黄现象；正式应用前需补充土壤检测、面积、品种和目标产量。"},
                    {"heading": "苗期方案", "body": "苗期以促进出苗和根系建立为主，建议少量多次补充氮磷钾基础肥，并结合地块墒情控制施用节奏。"},
                    {"heading": "分蘖期方案", "body": "分蘖期重点保证氮素供应和群体建立，可结合长势、叶色和缺肥表现安排追肥；偏酸地块应同步关注改良措施。"},
                    {"heading": "伸长期方案", "body": "伸长期是产量形成关键期，建议围绕水肥协同、钾肥补充和病虫风险监测形成阶段化管理清单。"},
                    {"heading": "风险处置", "body": "如出现脱肥发黄，应先核验土壤水分、根系状态和病虫害，再判断是否补肥；禁止仅凭单一表象直接加大用量。"},
                    {"heading": "计算说明", "body": "本地原型只保留规则计算接口位，真实用量应由规则计算引擎按面积、目标产量、土壤检测结果和肥料含量生成。"},
                ],
                "unresolved_questions": ["缺少土壤检测、面积、目标产量和肥料含量，当前只能作为专家方案结构初稿。"],
            }
        ],
    },
    "REQ-GENERIC-REPORT": {
        "title": "通用适配：报告/方案初稿",
        "l4_request": "根据上游资料和任务要求，生成一份结构化报告或方案初稿。",
        "content_type": "report_draft",
        "content_type_label": "报告/方案初稿",
        "requested_service": "生成报告/方案文字初稿",
        "template_id": "TPL-GENERIC-REPORT",
        "source_material_refs": ["DATA-GENERIC-CONTENT-INPUT"],
        "expected_output": "一份结构化报告/方案初稿",
        "review_policy": "direct_delivery_draft",
        "approval_template": [],
        "risk_level": "medium",
        "exit_policy": "direct_delivery",
        "mock_drafts": [
            {
                "title": "结构化报告/方案初稿",
                "sections": [
                    {"heading": "背景", "body": "围绕当前任务“{requirement}”整理背景和问题边界。"},
                    {"heading": "目标", "body": "明确本次成文目标、读者对象和预期用途；缺失信息应交回流程执行补齐。"},
                    {"heading": "主要内容", "body": "按照背景、现状、做法、风险、结论的顺序形成报告骨架。"},
                    {"heading": "风险与待确认", "body": "涉及事实、数字、结论和对外口径的部分需要引用上游资料，不由模型自行编造。"},
                ],
                "unresolved_questions": ["请确认报告用途、受众、关键依据资料和是否对外发布。"],
            }
        ],
    },
    "REQ-GENERIC-ARTICLE": {
        "title": "通用适配：文章/公众号初稿",
        "l4_request": "根据主题和资料生成一篇文章或公众号初稿。",
        "content_type": "article_draft",
        "content_type_label": "文章/公众号初稿",
        "requested_service": "生成文章/公众号文字初稿",
        "template_id": "TPL-GENERIC-ARTICLE",
        "source_material_refs": ["DATA-GENERIC-CONTENT-INPUT"],
        "expected_output": "一篇文章或公众号初稿",
        "review_policy": "direct_delivery_draft",
        "approval_template": [],
        "risk_level": "medium",
        "exit_policy": "direct_delivery",
        "mock_drafts": [
            {
                "title": "文章/公众号初稿",
                "sections": [
                    {"heading": "标题", "body": "围绕“{requirement}”拟定克制、清晰的标题。"},
                    {"heading": "开头", "body": "从目标读者关注的问题切入，说明本文要解决什么。"},
                    {"heading": "主体", "body": "分段展开核心信息，每段只表达一个要点，并保留资料引用位置。"},
                    {"heading": "结尾", "body": "收束主要观点，提示后续行动或待确认事项。"},
                ],
                "unresolved_questions": ["请确认目标读者、发布渠道、品牌口吻和引用资料。"],
            }
        ],
    },
    "REQ-GENERIC-MEETING": {
        "title": "通用适配：会议纪要/汇报稿",
        "l4_request": "根据会议记录整理纪要、汇报稿和待办。",
        "content_type": "meeting_summary",
        "content_type_label": "会议纪要/汇报稿",
        "requested_service": "整理会议纪要或汇报稿",
        "template_id": "TPL-GENERIC-MEETING",
        "source_material_refs": ["DATA-GENERIC-CONTENT-INPUT"],
        "expected_output": "会议纪要、汇报稿和待办清单",
        "review_policy": "direct_delivery_draft",
        "approval_template": [],
        "risk_level": "medium",
        "exit_policy": "direct_delivery",
        "mock_drafts": [
            {
                "title": "会议纪要/汇报稿初稿",
                "sections": [
                    {"heading": "会议背景", "body": "根据当前任务“{requirement}”提炼会议主题和讨论范围。"},
                    {"heading": "讨论要点", "body": "按议题拆分主要观点，保留分歧和待确认内容。"},
                    {"heading": "结论", "body": "只整理会议中已经形成的结论，不补造未讨论结论。"},
                    {"heading": "待办", "body": "列出责任人、事项、时间节点；缺失责任人时标记待补充。"},
                ],
                "unresolved_questions": ["请补充完整会议记录、参会人和已确认结论。"],
            }
        ],
    },
    "REQ-GENERIC-SCRIPT": {
        "title": "通用适配：话术/脚本初稿",
        "l4_request": "根据场景生成一份话术或脚本初稿。",
        "content_type": "script_draft",
        "content_type_label": "话术/脚本初稿",
        "requested_service": "生成话术/脚本文字初稿",
        "template_id": "TPL-GENERIC-SCRIPT",
        "source_material_refs": ["DATA-GENERIC-CONTENT-INPUT"],
        "expected_output": "一份话术或脚本初稿",
        "review_policy": "direct_delivery_draft",
        "approval_template": [],
        "risk_level": "medium",
        "exit_policy": "direct_delivery",
        "mock_drafts": [
            {
                "title": "话术/脚本初稿",
                "sections": [
                    {"heading": "场景", "body": "本脚本围绕当前任务“{requirement}”组织表达。"},
                    {"heading": "开场", "body": "先交代对象、目的和价值，不使用夸张承诺。"},
                    {"heading": "主体话术", "body": "按痛点、依据、解决方式、行动建议展开。"},
                    {"heading": "注意事项", "body": "涉及承诺、价格、效果、合规内容时，需要真人确认。"},
                ],
                "unresolved_questions": ["请确认使用场景、目标对象、语气和必须包含/禁止表达的内容。"],
            }
        ],
    },
    "REQ-GENERIC-DRAFT": {
        "title": "通用适配：文字初稿兜底",
        "l4_request": "根据任务要求生成一份通用文字初稿。",
        "content_type": "generic_text_draft",
        "content_type_label": "通用文字初稿",
        "requested_service": "生成通用文字初稿",
        "template_id": "TPL-GENERIC-DRAFT",
        "source_material_refs": ["DATA-GENERIC-CONTENT-INPUT"],
        "expected_output": "一份通用文字初稿",
        "review_policy": "direct_delivery_draft",
        "approval_template": [],
        "risk_level": "medium",
        "exit_policy": "direct_delivery",
        "mock_drafts": [
            {
                "title": "通用文字初稿",
                "sections": [
                    {"heading": "任务理解", "body": "当前任务为“{requirement}”，本引擎只能承办文字组织，不承办图片、视频、音频或跨引擎编排。"},
                    {"heading": "初稿内容", "body": "根据上游给定资料形成可继续修改的文字骨架。"},
                    {"heading": "引用与依据", "body": "正式使用时应补齐资料引用、数据来源和审核记录。"},
                    {"heading": "待补充信息", "body": "如需更准确产出，应由流程执行补齐能力类型、模板、目标受众、风格和引用资料。"},
                ],
                "unresolved_questions": ["请确认更精确的内容类型和必要资料。"],
            }
        ],
    },
    "MISSING-TPL": {
        "title": "异常路径：模板缺失导致无法办理",
        "l4_request": "生成一个目前没有配置模板的特殊对外声明。",
        "content_type": "unknown_statement",
        "content_type_label": "未配置文字成果",
        "requested_service": "生成特殊对外声明",
        "template_id": "TPL-MISSING",
        "source_material_refs": ["DATA-PRODUCT-001"],
        "expected_output": "特殊声明初稿",
        "review_policy": "pending_human_confirmation",
        "approval_template": ["品牌负责人"],
        "risk_level": "high",
        "exit_policy": "unable_to_handle",
        "mock_drafts": [],
    },
}

SUBTASK_REQUIRED_FIELDS = [
    ("caller_engine", "谁在调用"),
    ("requested_service", "请求哪项服务"),
    ("content_type", "请求类型"),
    ("input_brief", "传入内容"),
    ("expected_output", "期望返回"),
    ("trace_id", "追踪编号"),
]

WORKFLOW_STEPS = [
    {"key": "l4_request", "name": "外层 1：L4 员工提出请求", "phase": "outer", "layer": "L4", "module": "企业业务层"},
    {"key": "intent_analysis", "name": "外层 2：意图分析引擎识别文字产出任务", "phase": "outer", "layer": "L2", "module": "意图分析引擎"},
    {"key": "process_dispatch", "name": "外层 3：流程执行引擎拆分并派发子任务", "phase": "outer", "layer": "L2", "module": "流程执行引擎"},
    {"key": "receive_subtask", "name": "内部 1：接收并校验子任务六项字段", "phase": "inner", "layer": "L2", "module": "内容产出引擎"},
    {"key": "permission_precheck", "name": "内部 2：四要素权限与模板预校验", "phase": "inner", "layer": "L1/L2", "module": "1.1 权限 + 模板管理"},
    {"key": "classify_template", "name": "内部 3：判定内容类型并选定模板", "phase": "inner", "layer": "L2", "module": "内容类型与模板管理"},
    {"key": "fetch_context", "name": "内部 4：取得依据资料与上下文", "phase": "inner", "layer": "L1", "module": "1.7 数据 + 1.13 知识库"},
    {"key": "dispatch_model", "name": "内部 5：组装提示词并提交模型调度", "phase": "inner", "layer": "L1", "module": "1.6 提示词 + 1.5 大模型调度 + 1.12 成本"},
    {"key": "generate_draft", "name": "内部 6：生成结构化文字初稿", "phase": "inner", "layer": "L2", "module": "内容产出引擎"},
    {"key": "check_label_exit", "name": "内部 7：核查、标注与出口判定", "phase": "inner", "layer": "L2/L1", "module": "质量核查 + AI 标注"},
    {"key": "register_return", "name": "内部 8：成果登记并返回流程执行引擎", "phase": "inner", "layer": "L1/L2", "module": "1.7 数据三库 + 流程执行引擎"},
]

L1_MODULES = [
    {"id": "1.1", "name": "权限管理", "usage": "按当前操作真人校验读资料、用模板、生成、登记、交付"},
    {"id": "1.5", "name": "大模型调度", "usage": "提交文字生成任务，记录 model_task_id、排队、完成、失败"},
    {"id": "1.6", "name": "上下文与提示词管理", "usage": "按内容类型组装提示词、禁写规则、风格约束和引用要求"},
    {"id": "1.7", "name": "数据", "usage": "读取依据资料，登记文件库、结构化目录、语义库"},
    {"id": "1.12", "name": "成本管控", "usage": "估算 token、候选稿数量和成本提醒"},
    {"id": "1.13", "name": "知识库", "usage": "接收知识库问答引擎传入的法规、类案、品牌规范等引用"},
]

INTERFACE_CONTRACTS = [
    {
        "id": "receive_subtask",
        "method": "POST",
        "path": "/api/content-production/subtasks",
        "purpose": "接收流程执行引擎派发的内容产出子任务",
        "caller": "流程执行引擎",
        "permission_check": "接收后立即执行四要素权限预校验",
    },
    {
        "id": "task_status",
        "method": "GET",
        "path": "/api/content-production/tasks/{content_task_id}",
        "purpose": "查询任务状态、当前步骤、出口类型和阻断原因",
        "caller": "流程执行引擎/L4 状态页",
        "permission_check": "按任务可见范围控制",
    },
    {
        "id": "review_result",
        "method": "POST",
        "path": "/api/content-production/tasks/{content_task_id}/review-result",
        "purpose": "接收流程执行引擎返回的真人审核结果",
        "caller": "流程执行引擎",
        "permission_check": "审核人必须具备 confirm_result 动作权限",
    },
    {
        "id": "registry_preview",
        "method": "GET",
        "path": "/api/content-production/tasks/{content_task_id}/registry",
        "purpose": "查看文件库、结构化目录、语义库三类登记引用",
        "caller": "流程执行引擎/数据模块",
        "permission_check": "按登记结果可见范围控制",
    },
]

STATUS_SPEC = [
    {"code": "created", "label": "已创建", "terminal": False},
    {"code": "running", "label": "运行中", "terminal": False},
    {"code": "returned_for_completion", "label": "退回补齐", "terminal": True},
    {"code": "blocked_permission", "label": "权限阻断", "terminal": True},
    {"code": "preparing_context", "label": "准备上下文", "terminal": False},
    {"code": "dispatching_model", "label": "模型调度中", "terminal": False},
    {"code": "drafting", "label": "生成初稿中", "terminal": False},
    {"code": "checking", "label": "核查标注中", "terminal": False},
    {"code": "pending_human_confirmation", "label": "待真人确认", "terminal": False},
    {"code": "completed", "label": "已完成", "terminal": True},
    {"code": "unable_to_handle", "label": "无法办理", "terminal": True},
    {"code": "rejected", "label": "真人驳回", "terminal": True},
    {"code": "frozen", "label": "已冻结", "terminal": True},
]

ERROR_CODES = [
    {"code": "CP_001_MISSING_FIELD", "message": "缺少必填字段"},
    {"code": "CP_002_UNSUPPORTED_CONTENT_TYPE", "message": "内容类型不支持"},
    {"code": "CP_003_PERMISSION_DENIED", "message": "当前真人无权执行"},
    {"code": "CP_004_SOURCE_MATERIAL_MISSING", "message": "缺少依据资料"},
    {"code": "CP_005_TEMPLATE_NOT_FOUND", "message": "缺少模板"},
    {"code": "CP_006_DATA_SOURCE_CONFLICT", "message": "依据资料互相冲突"},
    {"code": "CP_007_MODEL_DISPATCH_FAILED", "message": "模型调度失败"},
    {"code": "CP_008_HUMAN_REVIEW_REQUIRED", "message": "命中必须真人审核规则"},
    {"code": "CP_009_SECURITY_POLICY_BLOCKED", "message": "安全策略阻断"},
    {"code": "CP_010_REGISTRY_FAILED", "message": "成果登记失败"},
]
