MODULES = {
    "engine-gateway": {"port": 8200, "interface": "/api/v1/engine/instructions", "implementation": "engine_gateway/service.py"},
    "intent-adapter": {"port": 8000, "interface": "/api/v1/intent/analyze", "implementation": "intent_analysis/service.py"},
    "intent-analysis-engine-original": {"port": 8003, "interface": "/api/v1/delivered-intent/analyze", "implementation": "intent_analysis/delivered_engine/service.py", "source": "联调文件-7.20-解压/intent-analysis-engine-handoff-20260720-173426"},
    "workflow-execution": {"port": 8020, "interface": "/api/v1/workflows/executions", "implementation": "workflow_execution/service.py"},
    "workflow-execution-engine-original": {"port": 8021, "interface": "/api/v1/delivered-workflow/instructions", "implementation": "workflow_execution/delivered_engine/service.py"},
    "rule-adapter": {"port": 8010, "interface": "/api/v1/rules/instructions", "implementation": "rule_calculation/service.py"},
    "rule-calculation-engine-original": {"port": 8012, "interface": "/api/v1/delivered-rules/calculate", "implementation": "rule_calculation/delivered_engine/service.py"},
    "content-adapter": {"port": 8011, "interface": "/api/v1/content/instructions", "implementation": "content_production/service.py"},
    "content-production-engine-original": {"port": 8013, "interface": "/api/v1/delivered-content/generate", "implementation": "content_production/delivered_engine/service.py"},
    "document-table-parsing": {"port": 8036, "interface": "/api/v1/document-table/instructions", "implementation": "document_table_parsing/service.py"},
    "analysis-prediction": {"port": 8030, "interface": "/api/v1/analysis/instructions", "implementation": "analysis_prediction/service.py"},
    "data-operation": {"port": 8031, "interface": "/api/v1/data/instructions", "implementation": "data_operation/service.py"},
    "digital-asset": {"port": 8032, "interface": "/api/v1/assets/instructions", "implementation": "digital_asset/service.py"},
    "project-management": {"port": 8033, "interface": "/api/v1/projects/instructions", "implementation": "project_management/service.py"},
    "monitoring-reminder": {"port": 8034, "interface": "/api/v1/monitoring/instructions", "implementation": "monitoring_reminder/service.py"},
    "external-system-integration": {"port": 8037, "interface": "/api/v1/external-systems/instructions", "implementation": "external_system_integration/service.py"},
    "knowledge-qa": {"port": 8038, "interface": "/api/v1/knowledge-qa/instructions", "implementation": "knowledge_qa/service.py"},
    "knowledge-map": {"port": 8039, "interface": "/api/v1/knowledge-map/instructions", "implementation": "knowledge_map/service.py"},
    "multimedia-generation": {"port": 8035, "interface": "/api/v1/multimedia/instructions", "implementation": "multimedia_generation/service.py"},
}
