appname = casdoor
httpport = 8000
runmode = prod

copyrequestbody = true
driverName = mysql
dataSourceName = root:casdoor@tcp(mysql:3306)/
dbName = casdoor
tableNamePrefix =
showSql = false
maxIdleConns = 10
maxOpenConns = 100

redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false

origin = http://localhost:8000
originFrontend = http://localhost:8000
staticBaseUrl =
sessionSecret = hanhe-casdoor-session-secret-change-me

isDemoMode = false
isReadonlyMode = false
enableGzip = true
enablePreview = false
enableErrorMask = false
enableEmailVerification = false
enableOrganizationInvitation = false
enableMultiTenant = false
enableSignup = false
enableSignin = true
defaultOrganization = hanhe
defaultApplication = app-built-in

logPostOnly = true
logSkip = false
logConfig = true
