PRAGMA foreign_keys = OFF;

CREATE TABLE IF NOT EXISTS organization (
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    created_time TEXT,
    display_name TEXT,
    website_url TEXT,
    logo TEXT,
    logo_dark TEXT,
    favicon TEXT,
    password_type TEXT,
    password_salt TEXT,
    password_options TEXT,
    password_expire_days INTEGER DEFAULT 0,
    country_codes TEXT,
    default_avatar TEXT,
    use_permanent_avatar INTEGER DEFAULT 0,
    default_application TEXT,
    user_types TEXT,
    tags TEXT,
    languages TEXT,
    master_password TEXT,
    default_password TEXT,
    ip_whitelist TEXT,
    init_score INTEGER DEFAULT 0,
    enable_soft_deletion INTEGER DEFAULT 0,
    is_profile_public INTEGER DEFAULT 0,
    use_email_as_username INTEGER DEFAULT 0,
    disable_signin INTEGER DEFAULT 0,
    ip_restriction TEXT,
    nav_items TEXT,
    user_nav_items TEXT,
    widget_items TEXT,
    mfa_items TEXT,
    mfa_remember_in_hours INTEGER DEFAULT 0,
    account_menu TEXT,
    account_items TEXT,
    dcr_policy TEXT,
    ldap_attributes TEXT,
    kerberos_realm TEXT,
    kerberos_kdc_host TEXT,
    kerberos_keytab TEXT,
    kerberos_service_name TEXT,
    org_balance REAL DEFAULT 0,
    user_balance REAL DEFAULT 0,
    balance_credit REAL DEFAULT 0,
    PRIMARY KEY (owner, name)
);

CREATE TABLE IF NOT EXISTS role (
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    created_time TEXT,
    display_name TEXT,
    description TEXT,
    users TEXT,
    groups TEXT,
    roles TEXT,
    domains TEXT,
    is_enabled INTEGER DEFAULT 1,
    PRIMARY KEY (owner, name)
);

CREATE TABLE IF NOT EXISTS user (
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    created_time TEXT,
    updated_time TEXT,
    id TEXT,
    type TEXT,
    password TEXT,
    password_salt TEXT,
    display_name TEXT,
    first_name TEXT,
    last_name TEXT,
    avatar TEXT,
    permanent_avatar TEXT,
    email TEXT,
    email_verified INTEGER DEFAULT 0,
    phone TEXT,
    country_code TEXT,
    region TEXT,
    location TEXT,
    address TEXT,
    affiliation TEXT,
    title TEXT,
    id_card_type TEXT,
    id_card TEXT,
    homepage TEXT,
    bio TEXT,
    tag TEXT,
    language TEXT,
    gender TEXT,
    birthday TEXT,
    education TEXT,
    score INTEGER DEFAULT 0,
    ranking INTEGER DEFAULT 0,
    is_default_avatar INTEGER DEFAULT 0,
    is_online INTEGER DEFAULT 0,
    is_admin INTEGER DEFAULT 0,
    is_forbidden INTEGER DEFAULT 0,
    is_deleted INTEGER DEFAULT 0,
    signup_application TEXT,
    hash TEXT,
    pre_hash TEXT,
    created_ip TEXT,
    last_signin_time TEXT,
    last_signin_ip TEXT,
    github TEXT,
    google TEXT,
    qq TEXT,
    wechat TEXT,
    facebook TEXT,
    dingtalk TEXT,
    weibo TEXT,
    gitee TEXT,
    linkedin TEXT,
    wecom TEXT,
    lark TEXT,
    gitlab TEXT,
    adfs TEXT,
    baidu TEXT,
    alipay TEXT,
    casdoor TEXT,
    infoflow TEXT,
    apple TEXT,
    azuread TEXT,
    slack TEXT,
    steam TEXT,
    bilibili TEXT,
    okta TEXT,
    douyin TEXT,
    custom TEXT,
    webauthn_credentials TEXT,
    preferred_mfa_type TEXT,
    recovery_codes TEXT,
    totp_secret TEXT,
    mfa_phone_enabled INTEGER DEFAULT 0,
    mfa_email_enabled INTEGER DEFAULT 0,
    multi_factor_auths TEXT,
    invitation TEXT,
    invitation_code TEXT,
    face_ids TEXT,
    ldap TEXT,
    properties TEXT,
    roles TEXT,
    permissions TEXT,
    groups TEXT,
    last_name2 TEXT,
    PRIMARY KEY (owner, name)
);

INSERT OR IGNORE INTO organization (
    owner, name, created_time, display_name, password_type, password_salt,
    password_options, country_codes, default_application, user_types, tags,
    languages, nav_items, user_nav_items, widget_items, account_items,
    mfa_items, ldap_attributes, enable_soft_deletion, is_profile_public,
    use_email_as_username, disable_signin
) VALUES (
    'admin', 'hanhe', datetime('now'), 'Hanhe', 'plain', '',
    '[]', '[]', 'app-built-in', '[]', '[]',
    '["zh","en"]', '[]', '[]', '[]', '[]',
    '[]', '[]', 0, 0,
    0, 0
);

INSERT OR IGNORE INTO role (
    owner, name, created_time, display_name, description, users, groups,
    roles, domains, is_enabled
) VALUES
    ('hanhe', 'admin', datetime('now'), 'Admin', 'Hanhe administrator role', '["hanhe/test-user"]', '[]', '[]', '[]', 1),
    ('hanhe', 'manager', datetime('now'), 'Manager', 'Hanhe manager role', '[]', '[]', '[]', '[]', 1),
    ('hanhe', 'staff', datetime('now'), 'Staff', 'Hanhe staff role', '[]', '[]', '[]', '[]', 1);

INSERT OR IGNORE INTO user (
    owner, name, created_time, updated_time, id, type, password,
    display_name, email, email_verified, language, score, ranking,
    is_default_avatar, is_online, is_admin, is_forbidden, is_deleted,
    signup_application, webauthn_credentials, recovery_codes,
    multi_factor_auths, face_ids, properties, roles, permissions, groups
) VALUES (
    'hanhe', 'test-user', datetime('now'), datetime('now'), 'hanhe-test-user', 'normal', '123',
    'Test User', 'test-user@hanhe.local', 1, 'zh', 0, 0,
    1, 0, 1, 0, 0,
    'app-built-in', '[]', '[]',
    '[]', '[]', '{}', '["admin"]', '[]', '[]'
);
