[request_definition]
r = sub, obj, typ, act, owner, tenant

[policy_definition]
p = sub, obj, typ, act, tenant, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (r.typ == "tool" && (r.act == "create" || r.act == "update") && r.sub == r.owner) || ((g(r.sub, p.sub) || r.sub == p.sub) && (p.obj == "*" || r.obj == p.obj) && (p.typ == "*" || r.typ == p.typ) && (p.act == "*" || r.act == p.act) && (p.tenant == "*" || r.tenant == p.tenant))
