services:
  l1-layer-interface:
    build: .
    ports:
      - "127.0.0.1:8002:8002"
    environment:
      L1_INTERFACE_HOST: 0.0.0.0
      L1_INTERFACE_PORT: 8002
      L1_INTERFACE_SERVICE_SECRET: ${L1_INTERFACE_SERVICE_SECRET:?set_a_secret}
      L1_INTERFACE_PERMISSION_URL: http://host.docker.internal:8001
      L1_INTERFACE_PERMISSION_MECHANISM_SECRET: ${PERMISSION_MECHANISM_SECRET:?set_a_secret}
      L1_INTERFACE_TARGET_SERVICE_SECRET: ${L1_INTERFACE_TARGET_SERVICE_SECRET:?set_a_secret}
      L1_INTERFACE_IDENTITY_CONTEXT_SECRET: ${L1_INTERFACE_IDENTITY_CONTEXT_SECRET:?set_a_secret}
