MODULES = {
    "template-management": {"port": 8004, "interface": "/api/v1/templates/instructions", "implementation": "template_management/service.py"},
    "foundation-gateway": {"port": 8300, "interface": "/api/v1/foundation/instructions", "implementation": "foundation_gateway/service.py"},
    "permission-adapter": {"port": 8001, "interface": "/api/v1/permissions/check", "implementation": "permission/service.py"},
    "model-dispatcher": {"port": 8002, "interface": "/api/v1/models/responses", "implementation": "model_dispatcher/service.py"},
    "capability-registry": {"port": 8400, "interface": "/api/v1/capabilities", "implementation": "capability_registry/service.py"},
    "context-prompt-management": {"port": 8059, "interface": "/api/v1/context-prompts/instructions", "implementation": "context_prompt_management/service.py"},
    "foundation-data": {"port": 8060, "interface": "/api/v1/foundation-data/instructions", "implementation": "foundation_data/service.py"},
    "account-gateway": {"port": 8050, "interface": "/api/v1/accounts/instructions", "implementation": "account_gateway/service.py"},
    "security-compliance": {"port": 8051, "interface": "/api/v1/security/instructions", "implementation": "security_compliance/service.py"},
    "human-collaboration": {"port": 8052, "interface": "/api/v1/human/instructions", "implementation": "human_collaboration/service.py"},
    "execution-sandbox": {"port": 8053, "interface": "/api/v1/sandbox/instructions", "implementation": "execution_sandbox/service.py"},
    "evolution-mechanism": {"port": 8054, "interface": "/api/v1/evolution/instructions", "implementation": "evolution_mechanism/service.py"},
    "control-mechanism": {"port": 8061, "interface": "/api/v1/control/instructions", "implementation": "control_mechanism/service.py"},
    "knowledge-base": {"port": 8055, "interface": "/api/v1/knowledge/instructions", "implementation": "knowledge_base/service.py"},
    "memory-management": {"port": 8062, "interface": "/api/v1/memory/instructions", "implementation": "memory_management/service.py"},
    "device-system-interface": {"port": 8063, "interface": "/api/v1/device-systems/instructions", "implementation": "device_system_interface/service.py"},
    "cost-control": {"port": 8064, "interface": "/api/v1/cost/instructions", "implementation": "cost_control/service.py"},
}
